### ISSUE TITLE
PR size autolabeling

### ISSUE THREAD

**Issue by patrickblackjr** [patrickblackjr/prow-lite#70]
PRs should be automatically labeled with the size based on the labels.

```yaml
- name: size
  category_color: 5319e7
  labels:
    - name: XS
      description: Denotes a PR that changes 0-9 lines.
    - name: S
      description: Denotes a PR that changes 10-29 lines.
    - name: M
      description: Denotes a PR that changes 30-99 lines.
    - name: L
      description: Denotes a PR that changes 100-499 lines.
    - name: XL
      description: Denotes a PR that changes 500-999 lines.
    - name: XXL
      description: Denotes a PR that changes 1000+ lines.
```
